version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "UTC"
    reviewers:
      - "@isasmendiagus"
      - "@dragonscan"
      - "@ortizjeronimo"
